### ISSUE TITLE
About the depth output

### ISSUE THREAD

**Issue by netbeifeng** [hustvl/TiNeuVox#10]
Hi,

Thanks for releasing the code.

I noticed that the depth derived by the model is not corresponding to the real world depth.
And it will also increase when the grid expands. 

I'd like to ask if there is any way to get depth derivation on the real world scale?

Thanks in advance.

**Comment by taoranyi** [comment]
There are similar problems in DirectVoxGo, you can check this [link](https://github.com/sunset1995/DirectVoxGO/issues/28)

**Comment by netbeifeng** [comment]
Thank you for sharing!
