### ISSUE TITLE
What does the add_cam mean?

### ISSUE THREAD

**Issue by chenerg** [hustvl/TiNeuVox#11]
I want to know what does the add_cam parameter do? Can you explain?

**Comment by chenerg** [comment]
Also, I'm confused abouth the pad used in grid_sample.

**Comment by taoranyi** [comment]
Since the hypernerf dataset uses two cameras, we use the add_cam paramete to distinguish different cameras.
The pad is added when sampling so that the grid can be divisible when downsampling.

**Comment by chenerg** [comment]
Thanks for your explanation! Great work!
