### ISSUE TITLE
how to generate render_demo.gif

### ISSUE THREAD

**Issue by liwenssss** [hustvl/TiNeuVox#13]
Hi, thanks for your nice work. Could you please tell me how to create render_demo.git to display the changes made during training?

**Comment by taoranyi** [comment]
Just render every few iterations.

**Comment by taoranyi** [comment]
In addition, the poses used in the demo are given [here](https://github.com/hustvl/TiNeuVox/blob/944e060a556e39f43a84d30d7cc1ff4a40c375ca/lib/load_dnerf.py#L123).
