### ISSUE TITLE
关于代码里的alpha的计算

### ISSUE THREAD

**Issue by RedemptYourself** [hustvl/TiNeuVox#16]
alpha = nn.Softplus()(density_result+self.act_shift)

之前有人提问 但是点的间隔并不是像解释那样恒定的 而是随着分辨率的增大会发生变化，是按照stepdist = stepsize * self.voxel_size 
   stepsize也就是0.5 这是恒定的，但stepdist并不恒定 两点之差= viewdir * stepdist

**Comment by RedemptYourself** [comment]
希望作者能够给予答复 万分感谢

**Comment by JaminFong** [comment]
感谢您指出这个问题，我们在代码中更新了这个地方，不过经过验证，这个问题对最终效果影响不大。
