### ISSUE TITLE
The reproduction of NSFF in the hypernerf_vrig dataset

### ISSUE THREAD

**Issue by xiaoyudanaa** [hustvl/TiNeuVox#21]
Hello author, thank you very much for such a good job. I have a request to ask you. One of my papers was reworked, and a reviewer asked me to add the results on hypernerf_vrig, but this was a bit difficult for me. So, I was wondering if you could send me your repro code on NSFF. Thank you very much.

**Comment by taoranyi** [comment]
Thank you for your attention. We have not been able to reproduce the results of NSFF. The results of NSFF in our paper on hypernerf_vrig are all based on the HyperNeRF paper.

**Comment by MELANCHOLY828** [comment]
> 你好，作者，非常感谢你如此出色的工作。我有一个请求要问你。我的一篇论文被重新修改了，一位审稿人要求我在 hypernerf_vrig 上添加结果，但这对我来说有点困难。所以，我想知道你是否可以把你在 NSFF 上的重现代码发给我。非常感谢。
Did you solve it? The data loading for Hyper is really hard to modify.
