### ISSUE TITLE
The version of pytorch

### ISSUE THREAD

**Issue by tykim5931** [hustvl/TiNeuVox#22]
Hello. I'm currently trying on your method and getting warning like
"warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")"

and error like "RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1."

It would be grateful if you could let me know what torch & cuda version you used, and also the GPU you used for running your code.

**Comment by taoranyi** [comment]
Hi! Thanks for your attention.
My environment is as follows：
Ubuntu 20.04.4 LTS
PyTorch version : 1.9.0
CUDA version : 11.1
torch_scatter : 2.0.9
GPU:RTX 3090
