### ISSUE TITLE
The baseline number of D-NeRF and T-NeRF.

### ISSUE THREAD

**Issue by Caoang327** [hustvl/TiNeuVox#3]
Hi. Great work!

I am curious that where the numbers of D-NeRF and T-NeRF reported in Table 1  come from? Are they from the officially pretrained model or do you train them again and evaluate the numbers?  I am asking because it seems that these numbers are much better than the reported numbers in the paper. Thanks

**Comment by JaminFong** [comment]
Thanks! The numbers of D-NeRF and T-NeRF are from [their paper](https://openaccess.thecvf.com/content/CVPR2021/papers/Pumarola_D-NeRF_Neural_Radiance_Fields_for_Dynamic_Scenes_CVPR_2021_paper.pdf), which are exactly the same.

**Comment by Caoang327** [comment]
Oh. They updated the numbers for the camera-ready version while I read the arxiv version. Sorry for the confusion.  Thanks
