### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by hibt29** [hustvl/TiNeuVox#4]
Hi, 

Thanks for releasing the code. 

When I run `python run.py --config configs/nerf-*/standup.py` to training,
Rasing this problem: `run.py: error: unrecognized arguments: configs/nerf-small/standup.py`

![run_problem](https://user-images.githubusercontent.com/107161929/173516101-a146982b-93c8-42aa-86b8-bf6c7b51bb9c.png)

So I tried `python run.py --config ./configs/nerf-*/standup.py` but got the same error.

![change_dir](https://user-images.githubusercontent.com/107161929/173516833-95a23135-6b10-4b46-ac7b-f62f57d5f1a8.png)

Do you occur this problem, and how to solve it ?

I'm running in the following environment
--
Ubuntu 20.04.4 LTS
PyTorch version : 1.10.2
CUDA version : 10.1

**Comment by hibt29** [comment]
Sorry, I typed `small` and it worked.
But when I ran it, I got this error `RuntimeError: Not compiled with CUDA support`.

I think my CUDA version may be different from yours.
So could you please tell me what version of PyTorch and CUDA you are using for this project?
I apologize if you have already described it somewhere.

Run Error Image
--

![run_error_1](https://user-images.githubusercontent.com/107161929/174421304-03a53112-f26a-435b-98cd-f9052a6dc650.png)
![run_error_2](https://user-images.githubusercontent.com/107161929/174421337-19b3a977-ef24-427c-bb97-7a2d287f973d.png)

**Comment by taoranyi** [comment]
My environment is as follows：
Ubuntu 20.04.4 LTS
PyTorch version : 1.9.0
CUDA version : 11.1
torch_scatter : 2.0.9

**Comment by taoranyi** [comment]
Hi! Thanks for your attention.
My environment is as follows：
Ubuntu 20.04.4 LTS
PyTorch version : 1.9.0
CUDA version : 11.1
torch_scatter : 2.0.9
