### ISSUE TITLE
novel view generation issue. overfitting?

### ISSUE THREAD

**Issue by hengfei-wang** [hustvl/TiNeuVox#5]
Hi,

Thank you for releasing the code. It is quite helpful to me.

I used my dataset which contains 140 iamges with different time stamps. But the images only from 14 training camera poses. Then I found the network can't generate good novel view images. I used the same dataset on D-nerf and it worked well. Are 14 training views too sparse for training the network? Have you found the same problem?

Thanks

**Comment by JaminFong** [comment]
Thanks for your attention!
 I have not yet met this problem. Could you show the failed generated images? Then I can better understand the problem.

**Comment by hengfei-wang** [comment]
Yes. I interpolated camera poses from pose1(the first image) to pose2(the second image). You can see that only trained poses can have a good render performance.

![000](https://user-images.githubusercontent.com/39575336/174570230-475d98a8-72db-4df6-8137-7388efcd323f.png)
![001](https://user-images.githubusercontent.com/39575336/174570237-768fac4a-7d40-4133-858b-6c8368c5d8fb.png)
![002](https://user-images.githubusercontent.com/39575336/174570240-2dfae132-ce0a-4ff7-a99e-598629846acf.png)
![003](https://user-images.githubusercontent.com/39575336/174570241-b90ae1a3-40dd-4551-86b0-48837ce87c70.png)
![004](https://user-images.githubusercontent.com/39575336/174570242-0099b879-bb6b-47fb-86f2-aae6e157b327.png)
![005](https://user-images.githubusercontent.com/39575336/174570245-5ff0f7a0-cca8-48aa-ae81-11f53f616a95.png)

**Comment by dsvilarkovic** [comment]
Have you solved this? I might have the same problem, but it makes no sense to me to not be able to generate novel views?

**Comment by hengfei-wang** [comment]
Hi @dsvilarkovic,

I haven't solved the problem. If you have any thoughts on this, please let me know.

**Comment by dsvilarkovic** [comment]
I solved it by converting my llff format camera poses to nerf/blender .json format with the script I found in torch-ngp https://github.com/ashawkey/torch-ngp/blob/main/scripts/llff2nerf.py

**Comment by hengfei-wang** [comment]
@dsvilarkovic 
Thank you for your solution. It solved my problem (not perfect but at least make sense). But I still don't get it. What cause this difference?

**Comment by dsvilarkovic** [comment]
To be honest, I do not know. \

**Comment by hengfei-wang** [comment]
OK, thanks.
