### ISSUE TITLE
A question about alpha value

### ISSUE THREAD

**Issue by RickyYXY** [hustvl/TiNeuVox#6]
In tineuvox.py at line 324, the alpha is calculated as alpha = nn.Softplus()(density_result+self.act_shift)
But it seems that the alpha should be alpha = 1 - exp(-density_result * dist)
I am confused by this, is this a kind of approximation?

**Comment by JaminFong** [comment]
Hi, following MipNeRF and DirectVoxGo, `softplus` is used for better optimization.

**Comment by RickyYXY** [comment]
Thanks for replying to me!
I see, but should it be: 
```
density = nn.Softplus()(density_result+self.act_shift)
alpha = 1 - exp(-density * dist) 
```?
MipNeRF and DirectVoxGo only changed the activate function from ReLU to Softplus, but they still need the dist to get alpha right?

**Comment by RickyYXY** [comment]
Sorry to bother you, but I still can't figure out this question...

**Comment by JaminFong** [comment]
Hey yeah, `dist` is omitted, which is yet constant as points are sampled with equal intervals in our implementation; so it leads to negligible effects. If you change to sample points in a different way, better follow the strict formulation to compute `alpha`.

**Comment by RickyYXY** [comment]
OK! I understand. Your code has helped me a lot. Thank you very much!
