### ISSUE TITLE
[question] deformation network 

### ISSUE THREAD

**Issue by yscoffee** [hustvl/TiNeuVox#7]
Thanks for open sourcing your great work!

Could you explain a bit why the deformation network does not require any regularization? e.g. small delta.

**Comment by JaminFong** [comment]
Hi, a regularization loss is added to suppress deformation for background points in hypernerf real scenes. In synthetic scenes, it is easy to model structures so this loss is omitted.
https://github.com/hustvl/TiNeuVox/blob/381f931df135b02f6c92e94594defbdc1f9b0afc/run.py#L451-L453

**Comment by yscoffee** [comment]
thanks for your explaination
