### ISSUE TITLE
About creation of dynamic scene data

### ISSUE THREAD

**Issue by FD29** [hustvl/TiNeuVox#8]
Hi,

Thanks for releasing the code.

I have two questions about creating data for dynamic scenes.

1. Will the data be created using Nerfies?

2. If we create data in Nerfies, how do we use the data created?

I would very much appreciate your consideration.

**Comment by taoranyi** [comment]
Thanks for your attention! 
We can use Nerfies to create datasets. You can see how Nerfies datasets are used [here](https://github.com/hustvl/TiNeuVox/blob/main/lib/load_hyper.py)

**Comment by rockywind** [comment]
Hi,
How to convert our data video to the training data style?
My data is collected by monocular camera on our collection car.
Our data style is similar to [Kitti dataset](https://www.cvlibs.net/datasets/kitti/).
